# Generated by Django 3.2.3 on 2021-05-22 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
