# Generated by Django 3.2.3 on 2021-05-23 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20210522_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
