# Generated by Django 3.2.3 on 2021-05-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_comment_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogx',
        ),
    ]
