# Generated by Django 3.2.3 on 2021-05-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_blog_comment_blogx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogx',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
