# Generated by Django 3.2.3 on 2021-05-29 17:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210523_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
